//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc2016.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class interests
    {
        public decimal id { get; set; }
        public string description { get; set; }
        public decimal users_id { get; set; }
        public bool active { get; set; }
    
        public virtual users users { get; set; }
    }
}
